version: 1.0.{build}
environment:
  appveyor_repo_tag: true
build_script:
- cmd: >-
    - SET PATH=C:\MinGW\bin;%PATH%
      - cmd: gcc test.c -o test.exe -lws2_32
artifacts:
- path: '*.*'
  name: test
deploy:
- provider: GitHub
  tag: test
  release: test
  auth_token:
    secure: EPk5lRvY+SRc5uziVGPxH7G/Xqmn+RX+th88P82UEbvXGYxhuEx7eYhcxDWdD98D
  artifact: '*.*'
  draft: false
  force_update: false
notifications:
- provider: Email
  to:
  - timsandhu@live.com
  subject: github compile & deploy
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true