version: 1.0.{build}
environment:

  with_zlib: 1      # libgd actually won't build without it..

  with_libpng: 1    # needs zlib; removing will break current tests

  with_libjpeg: 1   # will download nasm; removing will break current tests

  with_freetype: 1  # removing breaks bindings freetype test

  with_iconv: 0     

  with_tiff: 1      # needs zlib and jpeg
  
matrix:
    - build_platform: "x86"
	- build_compiler: "mingw"
	- build_bindings: 1

build_script:
  - if [%build_compiler%]==[mingw] if [%build_platform%]==[x86] SET PATH=C:\MinGW\bin;%PATH%
  - cmd: gcc test.c -o test.exe -lws2_32

  

 