version: 1.0.{build}
environment:
matrix:
    - build_platform: "x86"
    - build_compiler: "mingw"
    - build_bindings: 1

build_script:
  - if [%build_compiler%]==[mingw] if [%build_platform%]==[x86] SET PATH=C:\MinGW\bin;%PATH%
  - cmd: gcc test.c -o test.exe -lws2_32

  

 